# file: mysql/tasks/configure.yml

- name: MySQL | Update the my.cnf
  template:
    src: etc_mysql_my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: amol
    group: amol
    mode: 0644
  notify:
    - restart mysql
