---
- name: Copy nginx config
  sudo: yes
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/sites-available/{{name}}.conf

- name: Enable {{name}} site for nginx
  sudo: yes
  file: >
    src=/etc/nginx/sites-available/{{name}}.conf
    dest=/etc/nginx/sites-enabled/{{name}}.conf
    state=link
  notify: restart nginx