---
- hosts: 172.16.235.128
  remote_user: amol
  sudo: yes
  tasks:
    - name: symlink
      file: src=/etc/nginx/sites-available/website1 dest=/etc/nginx/sites-enabled/website1 owner=amol group=amol state=link
